### ISSUE TITLE
Scrape feed as soon as someone adds it.

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#112]
Don't need categories right away, but it would be good for users if their feeds get populated quickly.

**Comment by swglad** [comment]
Might need to go back to a queue system in order to do this effectively.

**Comment by swglad** [comment]
Steps:
1. Created ```scrape_only(feed)``` and ```categorize_only(feed)``` functions
2. Installed ```redis, rq``` (redis task queue)
3. Set up heroku with Nano version of RedisToGo add-on

**Comment by swglad** [comment]
Redis queue docs: http://python-rq.org/docs/

Notable: 
* ```at_front``` inserts a task to the FRONT of the queue
* multiple queue's can be named high/medium/low by priority, though I think we'll likely not use this feature since it'll max out connections

**Comment by swglad** [comment]
Need to run ```rqworker``` in order for the task queue to work (additional terminal command / line in .yml):  http://python-rq.org/

**Comment by swglad** [comment]
Also, fyi from https://devcenter.heroku.com/articles/redistogo#install-redis-in-python:

Troubleshooting

Why am I hitting my connection limit with one Dyno? This is often caused by customers using the nano free plan. One connection is used by one worker, but often other connections can be made to Redis. We would recommend upgrading to our lowest plan to see if this solves the issue. Otherwise we would recommend setting a hard limit on your application code.

**Comment by alexgerstein** [comment]
Can we use celery like before?

**Comment by swglad** [comment]
None of the heroku docs make any reference to Celery and this rq looks like it’ll be exactly what we’re looking for. I’d like to pursue this route first. If you look at the rq docs, it says: "
Project history
This project has been inspired by the good parts of Celery, Resqueand this snippet, and has been created as a lightweight alternative to existing queueing frameworks, with a low barrier to entry.
"

**Comment by alexgerstein** [comment]
Sounds good!

**Comment by swglad** [comment]
Looks like we need to install redis this way to get a server started: http://redis.io/topics/quickstart

**Comment by swglad** [comment]
But I'm not sure how to start a redis server within our code. I'm currently getting no connection errors because I can't get one set up. I've currently uninstalled redis and will wait for you so we can work on this together and get it done.

**Comment by alexgerstein** [comment]
The redis server needs to be started up in its own process; it can't run "within" our code. See: http://redis.io/topics/quickstart#starting-redis

**Comment by swglad** [comment]
Yes, I understand that. Let me clarify: By "within our code," I meant using config settings that we set in Sourcemash. Unless we're not supposed to do that and just assume the redis server is there and accepting connections
