### ISSUE TITLE
Check for updated_parsed before assigning last_updated on item.

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#139]
Maybe have a default to NOW() if updated_parsed doesn't exist.

**Comment by swglad** [comment]
Instead of just setting the feed's last updated at the end, update feed.last_updated with the most recently processed item.last_updated

try:
    item last updated
except:
    try:
         item publication date
    except:
          now

**Comment by swglad** [comment]
Change worker/scraper to ```continue``` instead of ```break``` if item_last_updated < feed_last_updated.
