### ISSUE TITLE
"Trending" items - backend

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#141]
Trending = absolute value of total votes cast, regardless of direction (e.g. number of upvote clicks + number of downvote clicks; not the same as VoteSum)

**Comment by swglad** [comment]
We may not want to sort by this, but may want to offer it as a view that users can select

**Comment by alexgerstein** [comment]
Agreed. I think it would be a nice feature to have on the landing page for new and registered users.

**Comment by swglad** [comment]
Should this be done with an API call that gets the top _X_ items in terms of totalVotesCast (in either direction)?

**Comment by alexgerstein** [comment]
I think that makes sense. That's an easy api call. Do we want to retrieve all trending items, or just ones that the user subscribed to?

**Comment by swglad** [comment]
Pass items through using the python render_template and play with "fun" HTML stuff woo
