### ISSUE TITLE
Loading Bar

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#147]
Categories (and now feeds too) take a while to calculate unread counts. Let's add a loading bar/circle so that the user knows the lists are on their way.

**Comment by swglad** [comment]
Should this be it's own view/template?

**Comment by alexgerstein** [comment]
I don't think it needs to be if we can just use a simple materialize component.

**Comment by swglad** [comment]
"No categories are assigned yet..." etc.
