### ISSUE TITLE
Allow user to use site without logging in

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#162]
Right now we say we can do that, but we actually can't.

"Dashboard" is login_required and every page (browse, feeds, categories) is accessed off of dashboard (e.g. dashboard#/browse). So, you can't actually ever get to these pages unless you're logged in. Even if you type in the URL, Flask-Security rejects you and sends you to the login page.

**Comment by alexgerstein** [comment]
Currently, all items for an un-authenticated user are marked as read; should be UNREAD (i.e. True).

**Comment by swglad** [comment]
Ties in with #172.

**Comment by swglad** [comment]
Done!
