### ISSUE TITLE
Modal to "Sign-up" for un-logged in users

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#165]

**Comment by swglad** [comment]
On a click to "Saved" or upvote.

**Comment by swglad** [comment]
1. Modal should have the register form inside it.

2. Navbar click on "I don't have an account" should bring up the subscribe modal.

3. Set Flask-Security Register Template to index.html, just like we did with login to kill the /login page.

**Comment by alexgerstein** [comment]
Also:

4) Adding feed urls.
