### ISSUE TITLE
Logo & favicon

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#184]
Working with Kevin Ozoria '17

**Comment by alexgerstein** [comment]
![logofinal](https://cloud.githubusercontent.com/assets/1390314/7328505/20e2ba4a-eaa4-11e4-93c9-8c3546f7d1f8.png)

![logotext](https://cloud.githubusercontent.com/assets/1390314/7328506/20e55b1a-eaa4-11e4-8126-70d17d07162d.png)


![solologo](https://cloud.githubusercontent.com/assets/1390314/7328507/20f139e4-eaa4-11e4-9ff5-7984fe6cb780.png)

![verticallogo](https://cloud.githubusercontent.com/assets/1390314/7328508/20f29000-eaa4-11e4-882f-4f129976a9e9.png)
