### ISSUE TITLE
Feedback from Michael (alpha)

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#203]
Skype call on Tuesday at 2pm

**Comment by swglad** [comment]
'1. Not immediately sure whether to set up a profile or whether it's going to be responsive immediately (add/delete/subscribe to feeds, categorization). *Set a persistence expectation*

**Comment by swglad** [comment]
'2. Is there a way to view all posts at the same time (all feeds views)? We're not sure if we want that. 

Design Thought: How much of the organization of our data do we want to expose?
* Users like to see everything and make their own choices
    * Make it seems like the users have choices (even if they post)
    * Allow "all posts" but have it actually be only the top 4 in every feed/category.

**Comment by swglad** [comment]
'3. Can't mark some feeds as read ****************** (e.g. specifically TechCrunch can't be marked as read ever)

**Comment by swglad** [comment]
'4. In the "tile view" on item card. Should be able to upvote/save INSIDE the card.

**Comment by swglad** [comment]
'5. Only place to add a feed currently is the Browse menu. Add a general button to add a feed. Perhaps put it in the sidebar underneath the collection.

**Comment by swglad** [comment]
'6. If there's a failed RSS feed, you don't get an error message as the user.

**Comment by swglad** [comment]
General RSS handling things
--------
* We can't fix all the bad issues, so we should have some sort of "this feed validates under our assumptions but isn't great". Ex: Reuters doesn't have images --> THROW THE RSS FEED UNDER THE BUS AND DONT MAKE IT LOOK LIKE ITS OUR APP'S FAULT
* Loading bar
* How do we feel about allowing users to rename feeds to be what they want it to be? 
    * Eg. "Free Republic" shows up as "Forum: News Activism"  --> allowing a user to rename
    * "My Name" in a user_feed table
    * Use favorited feeds for weighting when doing Multi Document Summarization 
           * Great validation on system b/c different summaries for same feeds

**Comment by swglad** [comment]
'7. Filtering so only show categories w/ at least XX items in it.

**Comment by swglad** [comment]
'8. Updated parsed time stamping error. Add dates ourselves.

**Comment by swglad** [comment]
'9. Sometimes unexpected behavior.
-------
* Punch reload/refresh: automatically sets you back to categories tab even if you're looking at a feed, and very briefly flashes the login screen. Not ideal.

**Comment by swglad** [comment]
** Michael didn't try to actively break the site ** - we should

**Comment by swglad** [comment]
'10. Some rando could create a really ugly, evil, disgusting feed that, when added, would show up on EVERYONE ELSE's browse page. 
---------------

**Comment by swglad** [comment]
Like to see an aggregate result of the voting --> what is the impact? Statistics/heat maps of articles, trending articles

**Comment by swglad** [comment]
Don't show the number of votes until you vote on it (sociological)

**Comment by swglad** [comment]
How should we represent categories?
- Take the top N categories by number of items and show them as titles
- Grab first google image search result as imagine for a category
~~~~~~~~~~~~~~~~
If categories are how we want people to use the site, what should we do?
- Tile view of top categories with some small number of top items within each category. "Big" visual is category and "small" visual is headline below that.
    * Tiles with lists, tiles with tiles inside them....play with it
    * Let people make a decision based on the content in the category, not exclusively the category name. 
           * Reproduce the user's "cluster of interest". 
           * Category --> Items --> Feeds in terms of usage

**Comment by swglad** [comment]
'11. Allow users to X-out categories and use the list of categories to just show and queue up new ones
* Makes users feel happy and in control

**Comment by swglad** [comment]
Generic things to keep in mind about categories
----------------------
* Homogeneity within a feed is massively important 
    * Feed is a data unit, but not a standard unit (NYTimes, 10k+ blog post, comic strips --> dealing with topic discovery is a tough issue that we should be cognizant of)

**Comment by swglad** [comment]
Long long long game: cut Feeds altogether 
* Only add a feed to get the articles to get the categories
* User responsibility: read stuff
     * First encounter and second encounter w/ the site should be different

**Comment by alexgerstein** [comment]
We created the related issues so we can now close this one.
