### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#204]
Look at http://www.sourcemash.com/api/feeds/2/items

Ctrl+F for ```"http://feeds.reuters.com/~r/reuters/businessNews/~3/rozLBPed638/story01.htm"```.

We shouldn't have the same item twice, even if the RSS feed has the same item twice.

**Comment by swglad** [comment]
We're definitely getting duplicates and it's definitely wrong. 

For example, there's are unique items in https://xkcd.com/rss.xml, but check out this screenshot:
![screen shot 2015-04-20 at 10 53 22 pm](https://cloud.githubusercontent.com/assets/5695548/7244863/f2d0bb08-e7af-11e4-85c9-a808e4c03019.png)

**Comment by alexgerstein** [comment]
Do you think we should check pub_date, instead of last_updated when scraping? It means we won't capture updated articles, but it should at least prevent the duplicates.

**Comment by swglad** [comment]
This was potentially resolved by #139, so look out.

**Comment by swglad** [comment]
This was resolved by #139.
