### ISSUE TITLE
Cut Feeds altogether

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#214]
But actually move it down to the sub-menu of the SideNav instead of having it be an equal tab.

Goal: user should only add a feed to get the articles to get the categories #203

**Comment by alexgerstein** [comment]
Call "feeds": "sources"

see #215.

**Comment by swglad** [comment]
I'm not sure how I feel about cutting feeds altogether yet. I think that we don't have a sufficiently good design structure in place for feeds, and I don't want to sacrifice the great UI work we have until that's in place.
