### ISSUE TITLE
Move production to DigitalOcean

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#233]
https://www.digitalocean.com/pricing/

And take advantage of being a student! https://education.github.com/pack.

Also, make sure to apply all of our add-ons (e.g. Redis)!

(Why? B/c we're running out of row space on Heroku.)
(Why only production? It's okay if staging fills up. We'll just clean up the db manually whenever it fills up)

**Comment by alexgerstein** [comment]
If no container error: "You should remove /home/dokku/proxy/PORT instead."
