### ISSUE TITLE
Category limit proportional to feeds subscribed

### ISSUE THREAD

**Issue by swglad** [sourcemash/Sourcemash#244]

**Comment by alexgerstein** [comment]
@swglad Idea: What do you think about picking categories from items in a feed as a way to decrease the number of categories? It's a little less hackish than this soluction.

**Comment by swglad** [comment]
Not sure what you mean

**Comment by alexgerstein** [comment]
So we use the categories assigned to all articles in a feed as the source of possible articles in each upcoming article. Kind of how we originally thought to do it with the bag-o-words approach.

**Comment by swglad** [comment]
That first sentence is still quite confusing….

**Comment by alexgerstein** [comment]
When we categorize an article, we use the categories from past articles in the feed as keyword candidates
