### ISSUE TITLE
Remove nested categories

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#272]

**Comment by alexgerstein** [comment]
@swglad Do we want to do this? For example, would we rather have Google Maps as a category over Google?

**Comment by swglad** [comment]
Yes. More often than not, it produces poor looking results instead of better. Moreover, it only usually happens when we use the simple word count algorithm instead of Wikipedia.

**Comment by alexgerstein** [comment]
OK. I'll work on this now then.
