### ISSUE TITLE
Username/Password errors indicated by where the errors appear.

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#39]
If you type in an incorrect password, the error "Invalid username/password combination" will show up below the password field.

However, if you type an incorrect username, it will show up below the email field.

So a hacker could figure out valid email addresses in our DB until we get the error messages to always appear in one place.

**Comment by alexgerstein** [comment]
This isn't resolved by #61.

**Comment by alexgerstein** [comment]
Rewrite our macro to generalize for all form types: http://stackoverflow.com/questions/23136081/how-to-override-flask-security-default-messages

**Comment by swglad** [comment]
http://stackoverflow.com/questions/20359578/flask-security-register-redirect

**Comment by swglad** [comment]
http://stackoverflow.com/questions/15685718/how-do-i-get-backbone-to-bind-the-submit-event-to-a-form/29465198#29465198

**Comment by swglad** [comment]
Converting form data to correct serialized form: http://stackoverflow.com/questions/1184624/convert-form-data-to-js-object-with-jquery 

Note: The method ```.serializeArray()``` does not format it correctly. We want ```{ email: "a@b", password: "c" }```, NOT ```{ {name: "email", value: "a@b"}, {name: "password", value: "c"} }```

**Comment by swglad** [comment]
In case we want these this macro later (for some reason):
```
{% macro fields_errors() %}
  {% for field in varargs %}
    {% if field.errors %}
      {% for error in field.errors %}
        <div class="alert alert-danger">{{error}}</div>
      {% endfor %}
    {% endif %}
  {% endfor %}
{% endmacro %}
<form class="col s12" id="login" action="/login" method="POST" name="login_user_form">
   ...
   {{ fields_errors(login_user_form.email, login_user_form.password, login_user_form.remember) }}
```
