### ISSUE TITLE
Set up separate production branch.

### ISSUE THREAD

**Issue by alexgerstein** [sourcemash/Sourcemash#58]
Also need travis.yml to run the functional tests when trying to push from 'master' to 'production'.

**Comment by swglad** [comment]
Do we want to set up an organizational heroku account and move both staging and production over to it?

**Comment by alexgerstein** [comment]
Before we worry about this, I think our biggest blocker for DevOps is #93. Let's work on that before we worry about setting up a production branch.

**Comment by swglad** [comment]
Set up organization accounts for both Github and Heroku

**Comment by alexgerstein** [comment]
Repo has been transferred to an organizational account on Github.

**Comment by alexgerstein** [comment]
Made a Heroku account for support@sourcemash.com. Need @swglad to transfer the Heroku project though because you're the owner.
